name: Docker Image Security Scan

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: hackops-enviro:test

      - name: Run Trivy vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          scan-ref: 'hackops-enviro:test'
          format: 'json'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.json'

      - name: Process Trivy results
        run: |
          if [ -s trivy-results.json ]; then
            echo "Processing Trivy scan results..."
            VULNERABILITIES=$(jq -r '.Results[].Vulnerabilities | length' trivy-results.json)
            if [ "$VULNERABILITIES" -gt 0 ]; then
              echo "⚠️ Found $VULNERABILITIES vulnerabilities:"
              jq -r '.Results[].Vulnerabilities[] | "\(.Severity) - \(.Title) (Package: \(.PkgName) \(.InstalledVersion))"' trivy-results.json
              echo "Continuing workflow despite vulnerabilities..."
            else
              echo "✅ No Critical or High severity vulnerabilities found."
            fi
          else
            echo "❌ No scan results found."
          fi

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.json 
