name: Main Branch CD

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Build Application
        run: npm run build

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hackops-enviro:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hackops-enviro:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/hackops-enviro:latest
            docker stop hackops-enviro || true
            docker rm hackops-enviro || true
            docker run -d --name hackops-enviro -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/hackops-enviro:latest

  security_scan:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Run npm audit
        run: npm audit

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'hackops-enviro'
          path: '.'
          format: 'HTML'
          out: 'reports'

      - name: Upload Security Report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: reports/

  monitoring:
    runs-on: ubuntu-latest
    needs: security_scan

    steps:
      - name: Set up New Relic
        run: |
          npm install newrelic
          echo "license_key: ${{ secrets.NEW_RELIC_LICENSE_KEY }}" > newrelic.yml
          
      - name: Configure New Relic
        run: |
          echo "app_name: hackops-enviro" >> newrelic.yml
          echo "log_level: info" >> newrelic.yml
